spring:
  application:
    name: product-service
  datasource:
    url: <url>
    username: <username>
    password: <password>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
server:
  port: 8081

#Eureka props  
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
