spring:
  application:
    name: product-service
  datasource:
    url: <url>
    username: <username>
    password: <password>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
server:
  port: 8081
  
