version: '3.8'
services:
  
  # MySQL DB
  inventory_db:
    image: mysql
    container_name: inventory_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=<db-name>
      - MYSQL_USER=<username> # don't use root as username, learnt it the hard way😫 exceptions 😫
      - MYSQL_PASSWORD=<password>
      - MYSQL_ROOT_PASSWORD=<root-password>
    # Where our data will be persisted  
    volumes:
      - ordermania_db_volume:/var/lib/mysql
      
  # APP BACKEND
  api_service:
    # Configuration for building the docker image for the backend service
    build: 
      context: . # Use an image built from the specified dockerfile in the directory.
      dockerfile: Dockerfile
    container_name: inventory_service_app
    ports:
      - 8080:8080 # mapping local machine port along with port inside a docker container.
    restart: always # Always restart the container if it stops
    environment: # Pass environment variables to the service
      - SPRING_DATASOURCE_URL=jdbc:mysql://inventory_mysql:3306/<db-name> # overwriting datasource_url in properties file 
    depends_on:
      - inventory_db  # This service depends on mysql. Start that first.

# Names our volume
volumes:
  ordermania_db_volume: